apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: q1qci7o73-python 
  janus-idp.io/tekton: q1qci7o73-python
  backstage.io/kubernetes-id: q1qci7o73-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q1qci7o73-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml